version: '3.8'

services:
  lf-fullstack-api:
    build: ./api
    restart: unless-stopped
    ports:
      - 8090:8090
    networks:
      - backend
      - frontend

  lf-fullstack-ui:
    depends_on:
      - lf-fullstack-api
    build:
      context: ./ui
      args:
        - REACT_APP_API_BASE_URL=http://backend:8090
    ports:
      - 3000:3000
    networks:
      - frontend  

networks:
  backend:
  frontend:
